perf: do not trigger change detection if there are no `scrolled` or `scrolledUp` observers
orizens/ngx-infinite-scroll pull request #409
Opened 2022-08-27 07:16 UTC by arturovt

2022-10-31 18:09 UTC, arturovt commented
Hey @orizens . Are you able to have look at this one?

2022-10-31 18:43 UTC, orizens requested changes
thanks for looking at the issue. please see my code refactor suggestion.

2022-10-31 18:43 UTC, orizens commented on projects/ngx-infinite-scroll/src/lib/ngx-infinite-scroll.directive.ts
> +    if (type === InfiniteScrollActions.DOWN && hasObservers(this.scrolled)) {
i would rather see something like that:

```typescript
let emitter;
switch (type) {
  case InfiniteScrollActions.DOWN:
    emitter = this.scrolled;
    return;

  case InfiniteScrollActions.UP:
     emitter = this.scrolledUp;
     return;

  default:
     return;
}
if (emitter & hasObservers(emitter)) {
   this.zone.run(() => emitter.emit(payload));
}
```

2022-11-01 19:10 UTC, arturovt commented on projects/ngx-infinite-scroll/src/lib/ngx-infinite-scroll.directive.ts
> +    if (type === InfiniteScrollActions.DOWN && hasObservers(this.scrolled)) {
Hey, I simplified it to a simpler version. There're no other types except `DOWN` and `UP` since they're mapped to `type: scrollDown ? InfiniteScrollActions.DOWN : InfiniteScrollActions.UP,`. It basically always defaulting to `UP` if scroll down if falsy.

2022-11-07 18:03 UTC, arturovt commented
@orizens friendly ping ;)

2022-11-07 19:28 UTC, orizens approved these changes

2022-11-07 19:29 UTC, merged

2022-11-07 19:32 UTC, orizens commented
@arturovt thanks or the pr
version 14.0.1 released